// <auto-generated />
using BitbucketSlackBot.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitbucketSlackBot.Migrations
{
    [DbContext(typeof(BitbucketSlackDataContext))]
    [Migration("20200806072441_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BitbucketSlackBot.Data.BitbucketRepository", b =>
                {
                    b.Property<int>("BitbucketRepositoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommonAccess")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Repository")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlackTeamID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workspace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BitbucketRepositoryID");

                    b.HasIndex("SlackTeamID");

                    b.ToTable("BitbucketRepository");
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.SlackTeam", b =>
                {
                    b.Property<string>("SlackTeamID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SlackTeamID");

                    b.ToTable("SlackTeam");
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.SlackUser", b =>
                {
                    b.Property<string>("SlackUserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlackTeamID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SlackUserID");

                    b.HasIndex("SlackTeamID");

                    b.ToTable("SlackUser");
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.SlackUserRepositoryAccess", b =>
                {
                    b.Property<string>("SlackUserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BitbucketRepositoryID")
                        .HasColumnType("int");

                    b.Property<int>("RepositoryAccess")
                        .HasColumnType("int");

                    b.HasKey("SlackUserID", "BitbucketRepositoryID");

                    b.HasIndex("BitbucketRepositoryID");

                    b.ToTable("SlackUserRepositoryAccess");
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.Subscriber", b =>
                {
                    b.Property<string>("SlackUserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BitbucketRepositoryID")
                        .HasColumnType("int");

                    b.Property<bool>("OnRepositoryCreated")
                        .HasColumnType("bit");

                    b.HasKey("SlackUserID", "BitbucketRepositoryID");

                    b.HasIndex("BitbucketRepositoryID");

                    b.ToTable("Subscriber");
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.BitbucketRepository", b =>
                {
                    b.HasOne("BitbucketSlackBot.Data.SlackTeam", "SlackTeam")
                        .WithMany("Repositories")
                        .HasForeignKey("SlackTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.SlackUser", b =>
                {
                    b.HasOne("BitbucketSlackBot.Data.SlackTeam", "SlackTeam")
                        .WithMany("Users")
                        .HasForeignKey("SlackTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.SlackUserRepositoryAccess", b =>
                {
                    b.HasOne("BitbucketSlackBot.Data.BitbucketRepository", "BitbucketRepository")
                        .WithMany("RepositoryAccesses")
                        .HasForeignKey("BitbucketRepositoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitbucketSlackBot.Data.SlackUser", "SlackUser")
                        .WithMany("RepositoryAccesses")
                        .HasForeignKey("SlackUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.Subscriber", b =>
                {
                    b.HasOne("BitbucketSlackBot.Data.BitbucketRepository", "BitbucketRepository")
                        .WithMany("Subscribers")
                        .HasForeignKey("BitbucketRepositoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitbucketSlackBot.Data.SlackUser", "SlackUser")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SlackUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
