// <auto-generated />
using System;
using BitbucketSlackBot.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitbucketSlackBot.Migrations
{
    [DbContext(typeof(BitbucketSlackDataContext))]
    [Migration("20200805162458_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BitbucketSlackBot.Data.BitbucketRepository", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommonAccess")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Repository")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlackTeamOwnerID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workspace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("SlackTeamOwnerID");

                    b.ToTable("BitbucketRepository");
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.SlackTeam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TeamID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SlackWorkspace");
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.SlackUser", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID", "TeamID");

                    b.HasIndex("TeamID");

                    b.ToTable("SlackUser");
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.SlackUserRepositoryAccess", b =>
                {
                    b.Property<int>("SlackUserID")
                        .HasColumnType("int");

                    b.Property<int>("BitbucketRepositoryID")
                        .HasColumnType("int");

                    b.Property<int>("RepositoryAccess")
                        .HasColumnType("int");

                    b.Property<int>("SlackUserID1")
                        .HasColumnType("int");

                    b.Property<int?>("SlackUserID2")
                        .HasColumnType("int");

                    b.Property<int>("SlackUserTeamID")
                        .HasColumnType("int");

                    b.Property<int?>("SlackUserTeamID1")
                        .HasColumnType("int");

                    b.HasKey("SlackUserID", "BitbucketRepositoryID");

                    b.HasIndex("BitbucketRepositoryID");

                    b.HasIndex("SlackUserID1", "SlackUserTeamID");

                    b.HasIndex("SlackUserID2", "SlackUserTeamID1");

                    b.ToTable("SlackUserRepositoryAccess");
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.Subscriber", b =>
                {
                    b.Property<int>("SlackUserID")
                        .HasColumnType("int");

                    b.Property<int>("BitbucketRepositoryID")
                        .HasColumnType("int");

                    b.Property<bool>("OnRepositoryCreated")
                        .HasColumnType("bit");

                    b.Property<int>("SlackUserID1")
                        .HasColumnType("int");

                    b.Property<int?>("SlackUserID2")
                        .HasColumnType("int");

                    b.Property<int>("SlackUserTeamID")
                        .HasColumnType("int");

                    b.Property<int?>("SlackUserTeamID1")
                        .HasColumnType("int");

                    b.HasKey("SlackUserID", "BitbucketRepositoryID");

                    b.HasIndex("BitbucketRepositoryID");

                    b.HasIndex("SlackUserID1", "SlackUserTeamID");

                    b.HasIndex("SlackUserID2", "SlackUserTeamID1");

                    b.ToTable("Subscriber");
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.BitbucketRepository", b =>
                {
                    b.HasOne("BitbucketSlackBot.Data.SlackTeam", "SlackTeamOwner")
                        .WithMany("Repositories")
                        .HasForeignKey("SlackTeamOwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.SlackUser", b =>
                {
                    b.HasOne("BitbucketSlackBot.Data.SlackTeam", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.SlackUserRepositoryAccess", b =>
                {
                    b.HasOne("BitbucketSlackBot.Data.BitbucketRepository", "Repository")
                        .WithMany("RepositoryAccesses")
                        .HasForeignKey("BitbucketRepositoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitbucketSlackBot.Data.SlackUser", "SlackUser")
                        .WithMany()
                        .HasForeignKey("SlackUserID1", "SlackUserTeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BitbucketSlackBot.Data.SlackUser", null)
                        .WithMany("RepositoryAccesses")
                        .HasForeignKey("SlackUserID2", "SlackUserTeamID1");
                });

            modelBuilder.Entity("BitbucketSlackBot.Data.Subscriber", b =>
                {
                    b.HasOne("BitbucketSlackBot.Data.BitbucketRepository", "Repository")
                        .WithMany("AllSubscribers")
                        .HasForeignKey("BitbucketRepositoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitbucketSlackBot.Data.SlackUser", "SlackUser")
                        .WithMany()
                        .HasForeignKey("SlackUserID1", "SlackUserTeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BitbucketSlackBot.Data.SlackUser", null)
                        .WithMany("AllSubscriptions")
                        .HasForeignKey("SlackUserID2", "SlackUserTeamID1");
                });
#pragma warning restore 612, 618
        }
    }
}
